name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build in docker
      run: docker build -t hello_world .
    - name: login to dockerhub
      run: docker login -u ${{ secrets.username }} -p ${{ secrets.password }}
    - name: add tag
      run: docker tag hello_world:latest rokkerdenis/hello_world:latest
    - name: push to dockerhub
      run: docker push rokkerdenis/hello_world

  tests:
    runs-on: ubuntu-latest
    services:
      dockerlhost:
        image: rokkerdenis/hello_world
        ports:
          - 8080:8080
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -v
